/*$file${.::UartMstr.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: uart_mstr.qm
* File:  ${.::UartMstr.c}
*
* This code has been generated by QM 5.2.5 <www.state-machine.com/qm>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* SPDX-License-Identifier: GPL-3.0-or-later
*
* This generated code is open source software: you can redistribute it under
* the terms of the GNU General Public License as published by the Free
* Software Foundation.
*
* This code is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
* FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
* more details.
*
* NOTE:
* Alternatively, this generated code may be distributed under the terms
* of Quantum Leaps commercial licenses, which expressly supersede the GNU
* General Public License and are specifically designed for licensees
* interested in retaining the proprietary status of their code.
*
* Contact information:
* <www.state-machine.com/licensing>
* <info@state-machine.com>
*/
/*$endhead${.::UartMstr.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#include "qpc.h"    /* QP/C framework API */
#include "bsp.h"    /* Board Support Package interface */
#include "UartMstr.h"

/* ask QM to declare the UartMstr class ------------------------------------*/
/*$declare${AOs::UartMstr} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::UartMstr} .........................................................*/
typedef struct {
/* protected: */
    QActive super;

/* private: */
    QTimeEvt te;
    uint8_t cmd;
    uint8_t retry;
    uint8_t rsp;
} UartMstr;

/* protected: */
static QState UartMstr_initial(UartMstr * const me, void const * const par);
static QState UartMstr_Active(UartMstr * const me, QEvt const * const e);
static QState UartMstr_RX(UartMstr * const me, QEvt const * const e);
static QState UartMstr_WAIT4CMD(UartMstr * const me, QEvt const * const e);
static QState UartMstr_ERR(UartMstr * const me, QEvt const * const e);
static QState UartMstr_TX(UartMstr * const me, QEvt const * const e);
static QState UartMstr_Idle(UartMstr * const me, QEvt const * const e);
/*$enddecl${AOs::UartMstr} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/* instantiate the Blinky active object ------------------------------------*/
static UartMstr l_uartMstr;
QActive * const AO_UartMstr = &l_uartMstr.super;

/* ask QM to define the Blinky class ---------------------------------------*/
/*$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/* Check for the minimum required QP version */
#if (QP_VERSION < 700U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 7.0.0 or higher required
#endif
/*$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/*$define${AOs::UartMstr_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::UartMstr_ctor} ....................................................*/
void UartMstr_ctor(void) {
    UartMstr *me = (UartMstr *)AO_UartMstr;
    QActive_ctor(&me->super, Q_STATE_CAST(&UartMstr_initial));
    QTimeEvt_ctorX(&me->te, &me->super, TIMEOUT_SIG, 0U);
    QS_OBJ_DICTIONARY(&me->te);
}
/*$enddef${AOs::UartMstr_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*$define${AOs::UartMstr} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::UartMstr} .........................................................*/

/*${AOs::UartMstr::SM} .....................................................*/
static QState UartMstr_initial(UartMstr * const me, void const * const par) {
    /*${AOs::UartMstr::SM::initial} */

    QS_FUN_DICTIONARY(&UartMstr_Active);
    QS_FUN_DICTIONARY(&UartMstr_RX);
    QS_FUN_DICTIONARY(&UartMstr_WAIT4CMD);
    QS_FUN_DICTIONARY(&UartMstr_ERR);
    QS_FUN_DICTIONARY(&UartMstr_TX);
    QS_FUN_DICTIONARY(&UartMstr_Idle);

    return Q_TRAN(&UartMstr_WAIT4CMD);
}

/*${AOs::UartMstr::SM::Active} .............................................*/
static QState UartMstr_Active(UartMstr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::UartMstr::SM::Active} */
        case Q_ENTRY_SIG: {
            BSP_Uart_Init();
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::UartMstr::SM::Active::initial} */
        case Q_INIT_SIG: {
            status_ = Q_TRAN(&UartMstr_WAIT4CMD);
            break;
        }
        /*${AOs::UartMstr::SM::Active::DISABLE} */
        case DISABLE_SIG: {
            status_ = Q_TRAN(&UartMstr_Idle);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

/*${AOs::UartMstr::SM::Active::RX} .........................................*/
static QState UartMstr_RX(UartMstr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::UartMstr::SM::Active::RX} */
        case Q_ENTRY_SIG: {
            QTimeEvt_armX(&me->te, 3*BSP_TICKS_PER_SEC, 0U);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::UartMstr::SM::Active::RX} */
        case Q_EXIT_SIG: {
            QTimeEvt_disarm(&me->te);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::UartMstr::SM::Active::RX::TIMEOUT} */
        case TIMEOUT_SIG: {
            --me->retry;
            /*${AOs::UartMstr::SM::Active::RX::TIMEOUT::[retry>0]} */
            if (me->retry > 0U) {
                status_ = Q_TRAN(&UartMstr_TX);
            }
            /*${AOs::UartMstr::SM::Active::RX::TIMEOUT::[else]} */
            else {
                status_ = Q_TRAN(&UartMstr_ERR);
            }
            break;
        }
        /*${AOs::UartMstr::SM::Active::RX::RSP} */
        case RSP_SIG: {
            BSP_ParseRsp(Q_EVT_CAST(RspEvt)->rsp);
            /* send response to other active objects */
            status_ = Q_TRAN(&UartMstr_WAIT4CMD);
            break;
        }
        default: {
            status_ = Q_SUPER(&UartMstr_Active);
            break;
        }
    }
    return status_;
}

/*${AOs::UartMstr::SM::Active::WAIT4CMD} ...................................*/
static QState UartMstr_WAIT4CMD(UartMstr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::UartMstr::SM::Active::WAIT4CMD} */
        case Q_ENTRY_SIG: {
            me->retry = 3;
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::UartMstr::SM::Active::WAIT4CMD::CMD} */
        case CMD_SIG: {
            me->cmd = Q_EVT_CAST(CmdEvt)->cmd;
            status_ = Q_TRAN(&UartMstr_TX);
            break;
        }
        default: {
            status_ = Q_SUPER(&UartMstr_Active);
            break;
        }
    }
    return status_;
}

/*${AOs::UartMstr::SM::Active::ERR} ........................................*/
static QState UartMstr_ERR(UartMstr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::UartMstr::SM::Active::ERR} */
        case Q_ENTRY_SIG: {
            /* uart error handler */
            QTimeEvt_armX(&me->te, BSP_TICKS_PER_SEC/10, 0U);
            BSP_UART_Error_Handler();
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::UartMstr::SM::Active::ERR::TIMEOUT} */
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&UartMstr_WAIT4CMD);
            break;
        }
        default: {
            status_ = Q_SUPER(&UartMstr_Active);
            break;
        }
    }
    return status_;
}

/*${AOs::UartMstr::SM::Active::TX} .........................................*/
static QState UartMstr_TX(UartMstr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::UartMstr::SM::Active::TX} */
        case Q_ENTRY_SIG: {
            BSP_UART_Receive();
            BSP_UART_Send(me->cmd);
            QTimeEvt_armX(&me->te, BSP_TICKS_PER_SEC/1, 0U);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::UartMstr::SM::Active::TX} */
        case Q_EXIT_SIG: {
            QTimeEvt_disarm(&me->te);

            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::UartMstr::SM::Active::TX::TX_DONE} */
        case TX_DONE_SIG: {
            status_ = Q_TRAN(&UartMstr_RX);
            break;
        }
        /*${AOs::UartMstr::SM::Active::TX::TIMEOUT} */
        case TIMEOUT_SIG: {
            --me->retry;
            /*${AOs::UartMstr::SM::Active::TX::TIMEOUT::[retry>0]} */
            if (me->retry > 0U) {
                status_ = Q_TRAN(&UartMstr_TX);
            }
            /*${AOs::UartMstr::SM::Active::TX::TIMEOUT::[else]} */
            else {
                status_ = Q_TRAN(&UartMstr_ERR);
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&UartMstr_Active);
            break;
        }
    }
    return status_;
}

/*${AOs::UartMstr::SM::Idle} ...............................................*/
static QState UartMstr_Idle(UartMstr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::UartMstr::SM::Idle} */
        case Q_ENTRY_SIG: {
            BSP_Uart_DeInit();
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::UartMstr::SM::Idle::ENABLE} */
        case ENABLE_SIG: {
            status_ = Q_TRAN(&UartMstr_Active);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*$enddef${AOs::UartMstr} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
